language: node_js
node_js:
  - '4'
sudo: required
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install -g codeclimate-test-reporter
install:
  - npm install
  - bower install
script:
  - 'COVERAGE=true ember try:each'
addons:
  code_climate:
    repo_token: 3c1dd3ff4af89209029ad977de3771056dcc5279a9df00c4ea697072edb4e7d6
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
dist: trusty
